on:
  push:
    branches:
      - main
  pull_request:
      types: [closed]
      branches:
          - main

name: Bundle and Publish Sources 
jobs:
  build:
    name: Bundle and Publish Sources
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm run bundle
      - run: npx typedoc -out bundles/docs
        continue-on-error: true

      - name: Deploy Sources
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: bundles
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - run: npm install
      - run: npm run bundle
      - run: npx typedoc -out bundles/docs

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"
          git checkout --orphan gh-pages
          git reset --hard
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
